#
# centos6-upstart:java7
#
#@  DOCKER_CONTAINER=""
#@  DOCKER_IMAGE_TAG="centos6-upstart:java7"
#@  DOCKER_BUILDOPTS="--build-arg jdk_version=7u80-b15"
#@  DOCKER_BOOT_OPTS=""
#
FROM centos6-upstart:java-onbuild

# Maintainer
MAINTAINER MT

# Labels for run
LABEL \
 docker.run.options="-d -P -h java7-machine" \
 docker.run.confirm-startup=""

