#
# centos7-systemd:java7
#
#@  DOCKER_CONTAINER=""
#@  DOCKER_IMAGE_TAG="centos7-systemd:java7"
#@  DOCKER_BUILDOPTS="--build-arg jdk_version=7u80-b15"
#@  DOCKER_BOOT_OPTS=""
#
FROM centos7-systemd:java-onbuild

# Maintainer
MAINTAINER MT

# Labels for run
LABEL \
 docker.run.options="-d -P -h java7-machine --privileged" \
 docker.run.confirm-startup=""

