#
# centos6-java:oracle-jdk7
#
#@  DOCKER_CONTAINER=""
#@  DOCKER_IMAGE_TAG="centos6-java:oracle-jdk7"
#@  DOCKER_BUILDOPTS="--build-arg JDK_VERSION=7u80-b15"
#@  DOCKER_BOOT_OPTS=""
#
FROM centos6-java:oracle

# Maintainer
MAINTAINER MT

# Labels for run
LABEL \
 docker.run.options="-d -P -h centos6javavm7" \
 docker.run.confirm-startup=""

