#
# centos6-init:java7
#
#@  DOCKER_CONTAINER=""
#@  DOCKER_IMAGE_TAG="centos6-init:java7"
#@  DOCKER_BUILDER_OPTS="--build-arg jdk_version=7u80-b15"
#@  DOCKER_STARTUP_OPTS="-h java7-machine"
#@  CONTAINER_NOT_START="yes"
#@  CONFIRM_STARTUP_CMD=""
#
FROM centos6-init:java-onbuild

# Maintainer
MAINTAINER MT

