#
# centos6-java:oracle-jdk
#
#@  DOCKER_CONTAINER=""
#@  DOCKER_IMAGE_TAG="centos6-java:oracle-jdk"
#@  DOCKER_BUILDOPTS="--build-arg JDK_VERSION="
#@  DOCKER_BOOT_OPTS=""
#
FROM centos6-java:oracle

# Maintainer
MAINTAINER MT

# Labels for run
LABEL \
 docker.run.options="-d -P -h centos6javavm" \
 docker.run.confirm-startup=""

