#
# centos7-java:java6
#
#@  DOCKER_CONTAINER=""
#@  DOCKER_IMAGE_TAG="centos7-java:java6"
#@  DOCKER_BUILDOPTS="--build-arg JDK_VERSION=6u45-b06 --build-arg JDK_PACKAGE_TYPE=bin"
#@  DOCKER_BOOT_OPTS=""
#
FROM centos7-java:java

# Maintainer
MAINTAINER MT

# Labels for run
LABEL \
 docker.run.options="-d -P -h java6-machine --privileged" \
 docker.run.confirm-startup=""

