#
# centos7-java:oracle-jdk8
#
#@  DOCKER_CONTAINER=""
#@  DOCKER_IMAGEPATH="centos7-java:oracle-jdk8"
#@  DOCKER_BUILDOPTS="--build-arg JDK_VERSION=8u112-b15"
#@  DOCKER_BOOT_OPTS=""
#
FROM centos7-java:oracle

# Maintainer
MAINTAINER MT

# Labels for run
LABEL \
 docker.run.options="-d -P -h centos7javavm8 --privileged" \
 docker.run.confirm-startup=""

