#
# centos6-upstart:java8
#
#@  DOCKER_CONTAINER=""
#@  DOCKER_IMAGE_TAG="centos6-upstart:java8"
#@  DOCKER_BUILDOPTS="--build-arg jdk_version=8u112-b15"
#@  DOCKER_BOOT_OPTS=""
#
FROM centos6-upstart:java-onbuild

# Maintainer
MAINTAINER MT

# Labels for run
LABEL \
 docker.run.options="-d -P -h java8-machine" \
 docker.run.confirm-startup=""

