#
# centos7-java:oracle-jdk
#
#@  DOCKER_CONTAINER=""
#@  DOCKER_IMAGE_TAG="centos7-java:oracle-jdk"
#@  DOCKER_BUILDOPTS="--build-arg JDK_VERSION="
#@  DOCKER_BOOT_OPTS=""
#
FROM centos7-java:oracle

# Maintainer
MAINTAINER MT

# Labels for run
LABEL \
 docker.run.options="-d -P -h javavm --privileged" \
 docker.run.confirm-startup=""

