#
# centos7-java:java7
#
#@  DOCKER_CONTAINER=""
#@  DOCKER_IMAGE_TAG="centos7-java:java7"
#@  DOCKER_BUILDOPTS="--build-arg JDK_VERSION=7u80-b15"
#@  DOCKER_BOOT_OPTS=""
#
FROM centos7-java:java

# Maintainer
MAINTAINER MT

# Labels for run
LABEL \
 docker.run.options="-d -P -h java7-machine --privileged" \
 docker.run.confirm-startup=""

