#
# centos6-java:oracle-jdk6
#
#@  DOCKER_CONTAINER=""
#@  DOCKER_IMAGE_TAG="centos6-java:oracle-jdk6"
#@  DOCKER_BUILDOPTS="--build-arg JDK_VERSION=6u45-b06 --build-arg JDK_PACKAGE_TYPE=bin"
#@  DOCKER_BOOT_OPTS=""
#
FROM centos6-java:oracle

# Maintainer
MAINTAINER MT

# Labels for run
LABEL \
 docker.run.options="-d -P -h centos6javavm6" \
 docker.run.confirm-startup=""

